### ISSUE TITLE
Solc compiler set latest despite explict environment setting

### ISSUE THREAD

**Issue by RyRy79261** [LimeChain/etherlime#115] opened 2018-11-27 11:26 UTC
## Expected behavior
This is my first run at EtherLime but I expected that after running the test command would compile and it fails to deploy due to compiler mismatch, I have force installed solc@0.4.24 both globally and locally in the project but the same issue persists

## Environment 
Windows 10 Latest

## Steps to reproduce
1. Globally install etherlime through npm as per docs
2. run `etherlime init` in a new directory
3. run `etherlime test`

Error:
`/contracts/LimeFactory.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.0+commit.1d4f565a.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;
^----------------------^`

**Comment by Perseverance** [comment] 2018-11-27 11:36
Hey, this is already fixed. Will be released with the latest etherlime version today. Thanks for noting it up :)

**Comment by Perseverance** [comment] 2018-11-27 11:49
ver 0.9.15 released. Closing this. Feel free to reopen it if it does not fix it

**Comment by RyRy79261** [comment] 2018-11-27 12:45
## 0.9.15 update

While the init project example test runs successfully with a listener error from ethers

Attempting to run test in repo with contracts with pragma set to below 0.5.0 encounter the same errors event with specifying `--solc-version=0.4.24`

**Comment by NikolayAngelov** [comment] 2018-11-27 18:21
> ## 0.9.15 update
> While the init project example test runs successfully with a listener error from ethers
> 
> Attempting to run test in repo with contracts with pragma set to below 0.5.0 encounter the same errors even with specifying `--solc-version=0.4.24`

The problem is that the `etherlime test` doesn't currently support specification of Solc Version and when running the `etherlime test` it compiles the contracts with the version provided in the `node_modules`

I think we can add support for `--solc-version` in `etherlime test` command which will be good for future use as well.

**Comment by Perseverance** [comment] 2019-01-05 14:50
Fixed in https://github.com/LimeChain/etherlime/pull/134 included in 0.10.2

**Closed** 2019-01-06 18:42 UTC
Labels: discussion, help wanted
